server:
  port: 8001
#mybatis的配置
mybatis:
  type-aliases-package: com.wang.springcloud.Dto
  cofig-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

#pring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

#Eureka配置 服务注册到哪里
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 # 修改Eureka上默认描述信息
#info配置
info:
  appName: wang-springcloud
  companyName: blog.wangstudy.com
