server:
  port: 7002

#Eureka配置
eureka:
  instance:
    hostname: eureka7002 #Eureka服务器的实例名称
  client:
    register-with-eureka: false #表示是否向Eureka注册中心注册自己
    fetch-registry: false #fetch-registry为false，则表示自己为注册中心
    service-url:   # 监控页面 this.serviceUrl.put("defaultZone", "http://localhost:8761/eureka/");
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7003:7003/eureka/
  server:
    enable-self-preservation: true #关闭Eureka自我保护机制
spring:
  application:
    name: DeptEurake7002