server:
  port: 9002


spring:
  application:
    name: DeptZuul-9002
eureka:
  instance:
    instance-id: DeptZuul9002.com
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
info:
  app.name: wang-springcloud
  company.name: www.wangStudy.com
zuul:
  routes:
    wang.serviceId: springcloud-provider-dept
    wang.patj: /wang/**
  ignored-services: "*" #springcloud-provider-dept 不能在使用这个路径访问了 ignored:忽略
  prefix: /wang #设置公共前缀
