server:
  port: 80
eureka:
  instance:
    appname: DeptConsumer-80
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
#fegin配置服务降级
feign:
  hystrix:
    enabled: true
