server:
  port: 3344
spring:
  application:
    name: springcloud-eureka
 #连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangzhiming971/springcloud.git #hhtps 不是ssh
#通过config-server可以连接到Gut 访问其中的资源和配置
